// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using W49_AssetTracking2;

#nullable disable

namespace W49AssetTracking2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221207132123_SeedingAssetData")]
    partial class SeedingAssetData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("W49_AssetTracking2.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Lenovo",
                            DateOfPurchase = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Ideacentre",
                            OfficeId = 2,
                            Price = 1530,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "HP",
                            DateOfPurchase = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Z2 Tower",
                            OfficeId = 3,
                            Price = 1490,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Lenovo",
                            DateOfPurchase = new DateTime(2022, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "ThinkPad X1",
                            OfficeId = 3,
                            Price = 580,
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2020, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Galaxy",
                            OfficeId = 1,
                            Price = 550,
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2022, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "S20",
                            OfficeId = 2,
                            Price = 180,
                            Type = "Phone"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            DateOfPurchase = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "iPhone 10",
                            OfficeId = 1,
                            Price = 250,
                            Type = "Phone"
                        });
                });

            modelBuilder.Entity("W49_AssetTracking2.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hardwares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Lenovo",
                            DateOfPurchase = new DateTime(2021, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Legion",
                            Price = 1600,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Acer",
                            DateOfPurchase = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Aspire XC",
                            Price = 1550,
                            Type = "Computer"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Apple",
                            DateOfPurchase = new DateTime(2021, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "MacBook",
                            Price = 650,
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2020, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "Galaxy",
                            Price = 550,
                            Type = "Laptop"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2022, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "S21",
                            Price = 200,
                            Type = "Phone"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Huawei",
                            DateOfPurchase = new DateTime(2019, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Model = "P30 Pro",
                            Price = 150,
                            Type = "Phone"
                        });
                });

            modelBuilder.Entity("W49_AssetTracking2.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CurrencyValue")
                        .HasColumnType("float");

                    b.Property<string>("LocalCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CurrencyValue = 1.0,
                            LocalCurrency = "USD"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Sweden",
                            CurrencyValue = 10.789999999999999,
                            LocalCurrency = "SEK"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Italy",
                            CurrencyValue = 0.98999999999999999,
                            LocalCurrency = "EUR"
                        });
                });

            modelBuilder.Entity("W49_AssetTracking2.Asset", b =>
                {
                    b.HasOne("W49_AssetTracking2.Office", "Office")
                        .WithMany("Hardwares")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("W49_AssetTracking2.Office", b =>
                {
                    b.Navigation("Hardwares");
                });
#pragma warning restore 612, 618
        }
    }
}
